all:
	# g++-10 -std=c++20 -I /Users/mt1ger/argobots/usr/include -I /Users/mt1ger/argobots-install/include -labt -L /Users/mt1ger/argobots-install/lib Plot.cpp txtParse.cpp -o Plot
	g++-11 -std=c++20 -pthread Plot.cpp txtParse.cpp -o Plot
